# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zoo_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_main = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_main.setGeometry(QtCore.QRect(30, 330, 741, 211))
        self.textBrowser_main.setObjectName("textBrowser_main")
        self.pushButton_mamifere = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mamifere.setGeometry(QtCore.QRect(70, 140, 151, 51))
        self.pushButton_mamifere.setObjectName("pushButton_mamifere")
        self.pushButton_enclos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enclos.setGeometry(QtCore.QRect(580, 140, 151, 51))
        self.pushButton_enclos.setObjectName("pushButton_enclos")
        self.pushButton_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quitter.setGeometry(QtCore.QRect(620, 280, 151, 51))
        self.pushButton_quitter.setObjectName("pushButton_quitter")
        self.pushButton_oiseau = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_oiseau.setGeometry(QtCore.QRect(240, 140, 151, 51))
        self.pushButton_oiseau.setObjectName("pushButton_oiseau")
        self.pushButton_poisson = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_poisson.setGeometry(QtCore.QRect(410, 140, 151, 51))
        self.pushButton_poisson.setObjectName("pushButton_poisson")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(170, 20, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_mamifere.setText(_translate("MainWindow", "Mamifère"))
        self.pushButton_enclos.setText(_translate("MainWindow", "Enclos"))
        self.pushButton_quitter.setText(_translate("MainWindow", "Quitter"))
        self.pushButton_oiseau.setText(_translate("MainWindow", "Oiseau"))
        self.pushButton_poisson.setText(_translate("MainWindow", "Poisson"))
        self.label_main.setText(_translate("MainWindow", "Paneau administrateur du zoo"))
